mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: a111111
    db: gin_blog
    log_level: error
logger:
    show_pass_line: true
server:
    host: 127.0.0.1
    port: "3030"
    env: dev
site_info:
    created_at: 2023.7.29
    bei_an: 川 xxxxx
    title: LiHao的个人博客
    addr: 成都
qq:
    app_id: sdfad
    key: dadd
    redirect: aaa
qiniu:
    access_key: your_qiniu_access_key
    secret_key: your_qiniu_secret_key
    bucket: your_bucket_name
    cdn: xxxx
    zone: xxxx
    size: 1
email:
    host: smtp.example.com
    port: 587
    user: user@example.com
    password: your_password
    default_from_email: xxx
    use_ssl: true
    user_tls: xxxxxxtls
jwt:
    secret: your_secret_key
    expires: 3600
    issuer: your_app_name
