server:
  # run-mode: 'release'
  host: 127.0.0.1
  port: 3030
  env: dev
  # read-timeout: 60
  # write-timeout: 60

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: a111111
  db: gin_blog

  # 可选[info, worn, error]
  # info: 每天sql日志都会在控制台打印处理
  # worn, error 会记录在日志文件中  适用于生产环境, 对日志的不同要求  worn: 会记录慢查询及error级别的错误, error 记录表不存在等错误
  log_level: error

  # table_prefix:


logger:
  show_pass_line: true            # 显示路径和行号


#配置文件
site_info:
  created_at: "2023.7.29"
  bei_an: 川xxxxx
  title: LiHao的个人博客
  addr: 成都





#redis:
#  host: '127.0.0.1:6379'
#  password: 'a111111'
#  max_idle: 30
#  max_active: 30
#  idle_timeout: 200
#
#
#
#wechat:
#  app_id:
#  app_secret:
#  token: yshop-gin
#  encoding_aes_key:
#
#express:
#  eBusinessId: 1607734
#  appKey: 81f43a2e-f504-45c4-9b54-2637d59f8190


email:
  host: smtp.example.com        # 邮件服务器主机名或IP地址
  port: 587                    # 邮件服务器端口
  user: user@example.com   # 邮件登录用户名
  password: your_password      # 邮件登录密码
  default_from_email: xxx
  use_ssl: true
  user_tls: xxxxxxtls

qiniu:
  access_key: your_qiniu_access_key       # 您的七牛云 Access Key
  secret_key: your_qiniu_secret_key       # 您的七牛云 Secret Key
  bucket: your_bucket_name           # 存储空间（Bucket）的名称
  cdn: xxxx
  zone: xxxx
  size: 1

qq:
  app_id: your_qq_client_id
  key: your_qq_client_secret
  redirect: your_callback_url

jwt:
  secret: your_secret_key
  expires: 3600
  issuer: your_app_name

es:
  host: localhost        # Elasticsearch 主机名或IP地址
  port: 9200             # Elasticsearch 端口
  username: your_username   # Elasticsearch 认证用户名（如果有的话）
  password: your_password   # Elasticsearch 认证密码（如果有的话）

redis:
  db: 0
  host: 127.0.0.1:6379
  password: a111111
