mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: a111111
    db: gin_blog
    log_level: info
logger:
    show_pass_line: true
server:
    host: 127.0.0.1
    port: "3030"
    env: dev
site_info:
    created_at: 2023.7.29
    bei_an: 川 xxxxx
    title: LiHao的个人博客
    addr: 成都
qq:
    app_id: "666"
    key: dadd
    redirect: aaa
qi_niu:
    enable: true  # 是否启用
    access_key: PkIfo3U5fGsC5tgiT2RHWEsVwU-bz6-vApT1rUkH
    secret_key: Dj3o1YUJSboe3N6oefpOyqyOyzryi6PV4A9cZIOz
    bucket: blog-gin-lihao
    cdn: ryz8iwkc6.hn-bkt.clouddn.com
    zone: z2
    size: 1
email:
    host: "333"
    port: 0
    user: lihao
    password: "21121"
    default_from_email: xxx
    use_ssl: true
    user_tls: 嘻嘻嘻
jwt:
    secret: your_secret_key
    expires: 3600
    issuer: your_app_name
upload:
    size: 1
    path: uploads/file
    white_list:
        - .jpg
        - .jpeg
        - .png
