server:
  # run-mode: 'release'
  host: 127.0.0.1
  port: 3030
  env: dev
  # read-timeout: 60
  # write-timeout: 60

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: a111111
  db: gin_blog
  log_level: dev
  # table_prefix:


logger:
  level: info
  prefix: '[gin]'
  director: log
  show-line: true            # 显示行号
  log-in-console: true       # 显示路径


app:
  page-size: 10
  jwt-secret: go-mall
  prefix-url: 'http://127.0.0.1:8000'
  runtime-root-path: 'runtime/'
  image-save-path: 'upload/images/'
  # MB
  image-max-size: 5242880
  image-allow-exts: ['.jpg','.jpeg','.png']
  export-save-path: 'export/'
  qrcode-save-path: 'qrcode/'
  font-save-path: 'fonts/'
  log-save-path: 'logs/'
  Log-save-name: 'log'
  Log-file-ext: 'log'
  time-format: 20060102



redis:
  host: '127.0.0.1:6379'
  password: 'a111111'
  max_idle: 30
  max_active: 30
  idle_timeout: 200



wechat:
  app_id:
  app_secret:
  token: yshop-gin
  encoding_aes_key:

express:
  eBusinessId: 1607734
  appKey: 81f43a2e-f504-45c4-9b54-2637d59f8190
